# Generated by Django 4.2.6 on 2023-10-25 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kelvin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
